stages:
  - front
  - back
  - dockerdeploy

dist: trusty
sudo: required

branches:
  only:
    - master
jobs:
  include:
  - stage: front
    language: node_js
    node_js:
      - 10
    addons:
      chrome: stable
    before_script:
      - cd / 
      - cd  /home/travis/build/mdevon19/LinkedIn-1/api/angular-linkedin
      - npm install -g @angular/cli
      - npm install    
    script:
      #- ng test --watch=false --no-progress --browsers=ChromeHeadless
      - ng build --prod
      
    workspaces:
      create:
        name: workspace1
        paths: /home/travis/build/mdevon19/LinkedIn-1/api
  - stage: back
    language: java
    jdk: oraclejdk8
    git:
      clone: false
    workspaces:
      use: workspace1
      create:
        name: workspace2
        paths: /home/travis/build/mdevon19/LinkedIn-1
    before_script:
      - cd /
      - cd  /home/travis/build/mdevon19/LinkedIn-1/api
    script:
      - ls ./angular-linkedin
      - mvn package -DskipTests
      - ls
      
  - stage: dockerdeploy
    language: generic
    git:
      clone: false
    workspaces:
        use: workspace1
        create:
          name: workspace3
          paths: /home/travis/build/mdevon19/LinkedIn-1
    before_script:
       - cd /
       - cd  /home/travis/build/mdevon19/LinkedIn-1

    services:
        - docker
    script:
        - ls
        - docker build -t linkedinfinal ./api
    after_success:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker images
        - docker tag linkedinfinal $DOCKER_USERNAME/linkedinfinal:latest
        - docker push $DOCKER_USERNAME/linkedinfinal:latest
        - cd /
        - cd  /home/travis/build/mdevon19/LinkedIn-1
        - git status
        
    deploy:
      provider: elasticbeanstalk
      access_key_id: $ACCESS_KEY_ID
      secret_access_key: $SECRET_ACCESS_KEY
      region: "us-east-2"
      app: "LinkedIn"
      env: "Linkedin-env"
      bucket_name: "elasticbeanstalk-us-east-2-317848226977"
      on:
        branch: master
